### ISSUE TITLE
PHP Fatal error:  Access level must be protected

### ISSUE THREAD

**Issue by nickweisser** [rokka-io/rokka-wordpress-plugin#29]
When I disable the Rokka plugin, I can upload files on /wp-admin/upload.php, but when it's enabled (PHP 7.2.22, WordPress 5.2.4, Rokka 3.0.1) there's an error message both on the browser console and the webserver logs:

`FastCGI: server "/var/run/hcgi/111535" stderr: PHP Fatal error:  Access level to Rokka\\Client\\Image::$defaultOrganization must be protected (as in class Rokka\\Client\\Base) or weaker in /wp-content/plugins/rokka-integration/vendor/rokka/client/src/Image.php on line 0, referer https://www.mysite.ch/wp-admin/upload.php`

**Comment by tschortsch** [comment]
Hi @nickw108. Thanks for the bug report. We sadly can't reproduce this error. The visibility of this field was changed in v1.7.0 of the `rokka-client-php` library. The plugin uses v1.8.0 of this library and higher since v3.0.0. Could you maybe look into this file `/wp-content/plugins/rokka-integration/vendor/rokka/client/CHANGELOG.md` and check which version you have? Maybe there was a problem updating the plugin?

**Comment by nickweisser** [comment]
Thanks for your feedback, @tschortsch. The change log lists 1.10.0 (2019-03-11) on top as the latest version. I re-installed the plugin and saw that various files were updated, although it was already version 3.0.1.

	modified:   wp-content/plugins/rokka-integration/assets/dist/admin.css
	modified:   wp-content/plugins/rokka-integration/assets/dist/admin.css.map
	modified:   wp-content/plugins/rokka-integration/assets/dist/admin.js
	modified:   wp-content/plugins/rokka-integration/assets/dist/admin.js.map
	deleted:    wp-content/plugins/rokka-integration/assets/dist/admin.map
	modified:   wp-content/plugins/rokka-integration/assets/dist/jquery-ui.min.css
	modified:   wp-content/plugins/rokka-integration/assets/dist/rokka-subject-area.js
	modified:   wp-content/plugins/rokka-integration/assets/dist/rokka-subject-area.js.map
	deleted:    wp-content/plugins/rokka-integration/assets/dist/rokka-subject-area.map
	modified:   wp-content/plugins/rokka-integration/assets/dist/settings.js
	modified:   wp-content/plugins/rokka-integration/assets/dist/settings.js.map
	deleted:    wp-content/plugins/rokka-integration/assets/dist/settings.map
	modified:   wp-content/plugins/rokka-integration/src/class-rokka-attachment.php
	modified:   wp-content/plugins/rokka-integration/src/class-rokka-rest.php
	modified:   wp-content/plugins/rokka-integration/src/class-wp-crop-bugfix.php
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/.gitignore
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/.travis.yml
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/INSTALL
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/LICENSE
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/README.md
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/URLify.php
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/composer.json
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/phpunit.xml
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/scripts/downcode.php
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/scripts/filter.php
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/scripts/transliterate.php
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/tests/URLifyTest.php
	modified:   wp-content/plugins/rokka-integration/vendor/jbroadway/urlify/tests/bootstrap.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/phpstan.neon
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/scripts/redirect_sami.html
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/scripts/run_sami_docs_locally.sh
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/scripts/run_sami_docs_on_travis.sh
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/scripts/sami-config.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/scripts/sami_highlight/layout/base.twig
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/scripts/sami_highlight/manifest.yml
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/Core/AbstractStack.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/Core/DynamicMetadata/CropArea.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/Core/DynamicMetadata/MultiAreas.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/Core/DynamicMetadata/Version.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/Core/StackAbstract.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/Core/StackExpression.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/Core/StackUri.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/Core/UriComponents.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/Image.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/LocalImage/AbstractLocalImage.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/LocalImage/FileInfo.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/LocalImage/RokkaHash.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/LocalImage/StringContent.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/TemplateHelper.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/TemplateHelper/AbstractCallbacks.php
	modified:   wp-content/plugins/rokka-integration/vendor/rokka/client/src/TemplateHelper/DefaultCallbacks.php

**Comment by nickweisser** [comment]
Forgot to mention that the problem was fixed 😬 Thanks for the pointer!
